### ISSUE TITLE
Use splunk 7.3.4 in Dockerfile

### ISSUE THREAD

**Issue by chriscasano** [timveil-cockroach/log-analyzer#5]
By using the latest splunk image it's pulling down a Redhat image causing the apt-get run commands to fail when building.  Instead, switch the dockerfile to use the 7.3.4 tag to get the debian based version.  BTW - Fantastic image.  Works like a charm otherwise.

**Comment by timveil** [comment]
finally got around to testing and fixing... updating base image to latest *debian* version... `8.0-debian`
